services:
  kindred-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "19199:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SQLITE_FILE_LOCATION=/app/db/server.db
      - JWT_SECRET=your-super-secret-jwt-key
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key
    volumes:
      - backend_data:/app/db/
    networks:
      - kindred_bridge
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/tasks/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_API_URL=https://track.cansu.dev/api/
    ports:
      - "19120:80"
    networks:
      - kindred_bridge
    depends_on:
      - kindred-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local

networks:
  kindred_bridge:
